---
name: Build and Publish Container Image

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    env:
      FEDORA_VERSION: "41"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check current branch
        if: github.ref != 'refs/heads/main'
        run: exit 0

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ghcr.io/led0nk/images
          oci: false
          build-args: |
            BASE_IMAGE=quay.io/fedora/fedora-silverblue
            FEDORA_VERSION=${{ env.FEDORA_VERSION }}
            XDG_RUNTIME_DIR=/run/user/1001

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request'
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_IMAGES }}
          extra-args: |
            --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        id: registry_login
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3.3.0
        if: github.event_name != 'pull_request'

      # Write signing key to disk because --env doesn't work (workaround)
      - name: write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Sign container image
        env:
          REGISTRY: ghcr.io
          COSIGN_EXPERIMENTAL: false
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ${{ steps.push.outputs.digest }}

        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key cosign.key $REGISTRY/${{ steps.build_image.outputs.image }}@${TAGS}
